/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import controlador.GestorDiagnostico;
import prolog.Prolog;

/**
 *
 * @author smuel
 */
public class JFInicio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFInicio.class.getName());
    prolog.Prolog pl = new Prolog();
    /**
     * Creates new form JFInicio
     */
    public JFInicio() {
        initComponents();
        try {
            pl.cargarBaseConocimiento();
        } catch (Exception e) {
            System.err.println("Error al cargar la base de conocimiento en JFInicio: " + e.getMessage());
            e.printStackTrace();
            // No detener la aplicación, continuar con la GUI
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnAgregarUsuario = new javax.swing.JButton();
        btnAgregarSintoma = new javax.swing.JButton();
        btnConsultarEnfermedades = new javax.swing.JButton();
        btnAgregarEnfermedad = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Sistema Experto");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Elige una opción");

        btnAgregarUsuario.setText("Agregar Usuario");
        btnAgregarUsuario.addActionListener(this::btnAgregarUsuarioActionPerformed);

        btnAgregarSintoma.setText("Agregar Sintoma");
        btnAgregarSintoma.addActionListener(this::btnAgregarSintomaActionPerformed);

        btnConsultarEnfermedades.setText("Consultar Enfermedades");
        btnConsultarEnfermedades.addActionListener(this::btnConsultarEnfermedadesActionPerformed);

        btnAgregarEnfermedad.setText("Agregar Enfermedad");
        btnAgregarEnfermedad.addActionListener(this::btnAgregarEnfermedadActionPerformed);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(this::btnSalirActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSalir)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(252, 252, 252)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnConsultarEnfermedades)
                                        .addComponent(btnAgregarUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnAgregarEnfermedad, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnAgregarSintoma, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(44, 44, 44)))))
                        .addGap(119, 119, 119)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(btnAgregarUsuario)
                .addGap(18, 18, 18)
                .addComponent(btnConsultarEnfermedades)
                .addGap(18, 18, 18)
                .addComponent(btnAgregarEnfermedad)
                .addGap(18, 18, 18)
                .addComponent(btnAgregarSintoma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarUsuarioActionPerformed
        new JFUsuario().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAgregarUsuarioActionPerformed

    private void btnConsultarEnfermedadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarEnfermedadesActionPerformed
        new JFEnfermedades().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnConsultarEnfermedadesActionPerformed

    private void btnAgregarEnfermedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarEnfermedadActionPerformed
        new JFAgregarEnfermedad().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAgregarEnfermedadActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAgregarSintomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarSintomaActionPerformed
        new JFAgregarSintoma().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAgregarSintomaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFInicio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarEnfermedad;
    private javax.swing.JButton btnAgregarSintoma;
    private javax.swing.JButton btnAgregarUsuario;
    private javax.swing.JButton btnConsultarEnfermedades;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
