/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JCheckBox;
import controlador.GestorDiagnostico;
import javax.swing.BoxLayout;
import javax.swing.JPanel;
import javax.swing.JOptionPane;
import javax.swing.BoxLayout;
import javax.swing.JPanel;
import javax.swing.JFileChooser;
import java.io.File;
import java.awt.Component;

import controlador.GestorDiagnostico;
import controlador.GestorSintoma;
import models.Paciente;
import prolog.Prolog;
/**
 *
 * @author smuel
 */
public class JFSintomas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFSintomas.class.getName());
    private String nombrePaciente;
    private int edadPaciente;
    
    // Lista dinámica para guardar las referencias a los checkboxes generados
    private List<JCheckBox> listaCheckBoxesGenerados = new ArrayList<>();

    // Componentes manuales
    private javax.swing.JPanel panelCheckboxes; 
    private javax.swing.JTextArea txtAreaResultados; 
    private javax.swing.JScrollPane scrollResultados;
    
    public JFSintomas() {
        initComponents();
        inicializarComponentesPersonalizados();
    }
    public JFSintomas(String nombre, int edad) {
        initComponents();        
        this.nombrePaciente = nombre;
        this.edadPaciente = edad;
        inicializarComponentesPersonalizados();
        // cargarSintomas();
    }
    
    private void inicializarComponentesPersonalizados() {
        
        // --- 1. Crear Panel Contenedor de Síntomas ---
        panelCheckboxes = new JPanel();
        panelCheckboxes.setLayout(new BoxLayout(panelCheckboxes, BoxLayout.Y_AXIS)); 
        
        // --- 2. Cargar Síntomas Dinámicamente desde la BD ---
        GestorSintoma gestorSintoma = new GestorSintoma();
        List<String> sintomasBD = gestorSintoma.obtenerTodosLosSintomas();
        
        if (sintomasBD.isEmpty()) {
            panelCheckboxes.add(new javax.swing.JLabel("No hay síntomas cargados en la base de datos."));
        } else {
            for (String sintoma : sintomasBD) {
                // Crear un checkbox por cada síntoma
                // 'sintoma' viene legible (ej: "dolor de cabeza")
                JCheckBox chk = new JCheckBox(sintoma);
                listaCheckBoxesGenerados.add(chk); // Guardarlo en la lista para revisarlo luego
                panelCheckboxes.add(chk);          // Añadirlo visualmente
            }
        }
        
        // Establecer el panel dentro del ScrollPane
        panelSintomas.setViewportView(panelCheckboxes);
        
        // --- 3. Inicializar Área de Resultados ---
        txtAreaResultados = new javax.swing.JTextArea();
        scrollResultados = new javax.swing.JScrollPane();
        txtAreaResultados.setColumns(20);
        txtAreaResultados.setRows(5);
        txtAreaResultados.setEditable(false);
        scrollResultados.setViewportView(txtAreaResultados);
        
        // --- 2. Crear Panel Contenedor de Síntomas ---
        panelCheckboxes = new JPanel();
        panelCheckboxes.setLayout(new BoxLayout(panelCheckboxes, BoxLayout.Y_AXIS)); // Layout Vertical
        
        // Agregar los checkboxes al panel
        for (JCheckBox chk : listaCheckBoxesGenerados) {
            panelCheckboxes.add(chk);
        }
        
        // Establecer el panel de checkboxes dentro del JScrollPane de síntomas
        panelSintomas.setViewportView(panelCheckboxes);
        
        
        // --- 3. Inicializar Área de Resultados (TAREA 2) ---
        txtAreaResultados = new javax.swing.JTextArea();
        scrollResultados = new javax.swing.JScrollPane();
        
        txtAreaResultados.setColumns(20);
        txtAreaResultados.setRows(5);
        txtAreaResultados.setEditable(false);
        scrollResultados.setViewportView(txtAreaResultados);
        
        btnExportarCSV = new javax.swing.JButton("Exportar a CSV");
        btnExportarCSV.addActionListener(evt -> btnExportarCSVActionPerformed(evt));
        // Añadir el scrollResultados al layout de la ventana

    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        panelSintomas = new javax.swing.JScrollPane();
        btnDiagnosticar = new javax.swing.JButton();
        btnExportarCSV = new javax.swing.JButton();
        Regresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Seleccione los sintomas");

        btnDiagnosticar.setText("Diagnosticar");
        btnDiagnosticar.addActionListener(this::btnDiagnosticarActionPerformed);

        btnExportarCSV.setText("Exportar");
        btnExportarCSV.addActionListener(this::btnExportarCSVActionPerformed);

        Regresar.setText("Regresar");
        Regresar.addActionListener(this::RegresarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Regresar)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1)
                        .addContainerGap(105, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(panelSintomas)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnExportarCSV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDiagnosticar)
                        .addGap(36, 36, 36))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Regresar))
                .addGap(22, 22, 22)
                .addComponent(panelSintomas, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDiagnosticar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExportarCSV))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDiagnosticarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiagnosticarActionPerformed
        int id = 1; 
        models.Paciente paciente = new models.Paciente(id, this.nombrePaciente, this.edadPaciente);
        
        List<String> sintomasSeleccionados = new ArrayList<>();
        
        // Recorrer los checkboxes dinámicos
        for (JCheckBox chk : listaCheckBoxesGenerados) {
            if (chk.isSelected()) {
                // Convertir el texto legible a formato Prolog (snake_case)
                // Ej: "Dolor de Cabeza" -> "dolor_de_cabeza"
                String sintomaProlog = chk.getText().toLowerCase().replace(" ", "_");
                sintomasSeleccionados.add(sintomaProlog);
            }
        }
        
        if (sintomasSeleccionados.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Seleccione al menos un síntoma.");
            return;
        }
        
        GestorDiagnostico gestor = new GestorDiagnostico(); 
        
        prolog.Prolog pl = new Prolog();
        pl.cargarBaseConocimiento(); 
        

        
        // Asegurar que la base de conocimiento está cargada
        // (Si usas la clase Prolog.java para esto, llámala, si no, GestorDiagnostico debería encargarse)
        // gestor.cargarBaseConocimiento(); // Si tienes este método
        
        // Obtener y mostrar diagnóstico
        String resultado = gestor.obtenerDiagnostico(paciente, sintomasSeleccionados);
        txtAreaResultados.setText(resultado);
        
        // Mostrar el scroll de resultados si estaba oculto
        if (scrollResultados.getParent() == null) {
             // Lógica simple para añadirlo al final si no estaba en el diseño
             javax.swing.GroupLayout layout = (javax.swing.GroupLayout) getContentPane().getLayout();
             // (Ajustar layout programáticamente es complejo, mejor agrégalo en el DESIGN)
             JOptionPane.showMessageDialog(this, resultado, "Diagnóstico", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_btnDiagnosticarActionPerformed

    private void btnExportarCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarCSVActionPerformed
        if (txtAreaResultados.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Primero debe realizar un diagnóstico.");
            return;
        }

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Guardar Diagnóstico como CSV");
        fileChooser.setSelectedFile(new File("diagnostico.csv"));
        
        int userSelection = fileChooser.showSaveDialog(this);
        
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();
            // Asegurar extensión .csv
            if (!fileToSave.getAbsolutePath().endsWith(".csv")) {
                fileToSave = new File(fileToSave.getAbsolutePath() + ".csv");
            }
            
            // Recolectar datos nuevamente para exportar
            int id = 1;
            models.Paciente paciente = new models.Paciente(id, this.nombrePaciente, this.edadPaciente);
            List<String> sintomasSeleccionados = new ArrayList<>();
            for (JCheckBox chk : listaCheckBoxesGenerados) {
                if (chk.isSelected()) {
                    sintomasSeleccionados.add(chk.getText().toLowerCase().replace(" ", "_"));
                }
            }
            
            GestorDiagnostico gestor = new GestorDiagnostico();
            boolean exito = gestor.exportarDiagnosticoCSV(paciente, sintomasSeleccionados, fileToSave);
            
            if (exito) {
                JOptionPane.showMessageDialog(this, "Archivo guardado exitosamente en:\n" + fileToSave.getAbsolutePath());
            } else {
                JOptionPane.showMessageDialog(this, "Error al guardar el archivo.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnExportarCSVActionPerformed

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        new JFUsuario().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFSintomas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Regresar;
    private javax.swing.JButton btnDiagnosticar;
    private javax.swing.JButton btnExportarCSV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane panelSintomas;
    // End of variables declaration//GEN-END:variables
}
